### ISSUE TITLE
New auto-discovery-templates

### ISSUE THREAD

**Issue by bob-tm** [igor-podpalchenko/ha-devi-mqtt#5]
I updated auto-discovery-templates.
[auto-discovery-templates.zip](https://github.com/user-attachments/files/17460451/auto-discovery-templates.zip)

1. New entity name format: devireg_{serial}. This allow to rename all device entities with device renaming. All json files + autogen-sensors.py was updated.
2. Add uniquie_id prefix, to apply changes from entity rename.
3. Add unit_of_measurement for some sensors + device_class
4. there is postfix "db" in sys_wifi_strength data (-64 db). Please remove it, so I can set proper device_class in template
5. sensor.devireg_xxxx_sys_run_time reported as string. I think it is better to use unix time or just seconds with proper device_class on ha side.

**Comment by bob-tm** [comment]
[auto-discovery-templates.zip](https://github.com/user-attachments/files/17474979/auto-discovery-templates.zip)
Fix for control state and new active set point sensor

**Comment by igor-podpalchenko** [comment]
I've sent you an invitation to contribute to the project. I'm not currently actively working on it, so if you can make some improvements - you are welcome.

**Comment by bob-tm** [comment]
Thank you. I almost finished. 

I need some help, because it's my first experience with  java language :)

In DeviRegHandler.java  I need to read current  CHANNEL_SETPOINT_COMFORT, CHANNEL_SETPOINT_ECONOMY, etc  temp values.

Do I need to declare some private variable and store values to it as they changed or there is some method like self.get_temperature(CHANNEL_SETPOINT_COMFORT) ?

**Comment by bob-tm** [comment]
Everything works as excepted.  
New code in fork https://github.com/bob-tm/ha-devi-mqtt
if everything will be ok - I will upload changes in this repo.

**Comment by bob-tm** [comment]
I make pull request with all my  changes. Please check it.  
There is some docker login errors. I have no idea what is this.

**Comment by igor-podpalchenko** [comment]
It is checked and merged. Please check Docker image. Thanks for your work.
